service: valentine-gacha

provider:
  name: aws
  runtime: python3.6
  region: ap-northeast-1
  apiKeys:
    - vaentine-gacha-key
  environment:
    ${file(./conf/env.yml)}

functions:
  select_random_user:
    handler: handler.select_random_user
    timeout: 30
    events:
      - http:
          path: /users/random
          method: post
          private: true
          cors: true
          integration: lambda
          request:
            template:
              application/json: '{ "name" : $input.json("$.name"), "number" : $input.json("$.number") }'
  notice_slack:
    handler: notice_slack.handler
    timeout: 30
    events:
      - http:
          path: /slack/notice
          method: post
          private: true
          cors: true
          integration: lambda
          request:
            template:
              application/json: '{ "presenter_name" : $input.json("$.presenter_name"), "winners_id" : $input.json("$.winners_id") }'

plugins:
  - serverless-python-requirements