service: valentine-gacha

provider:
  name: aws
  runtime: python3.6
  region: ap-northeast-1
  apiKeys:
    - vaentine-gacha-key

functions:
  select_random_user:
    handler: handler.select_random_user
    timeout: 60
    events:
      - http:
          path: /users/random
          method: post
          private: true
          cors: true
          integration: lambda
          request:
            template:
              application/json: '{ "name" : $input.json("$.name"), "number" : $input.json("$.number") }'

plugins:
  - serverless-python-requirements